### ISSUE TITLE
zhanziyuangao

### ISSUE THREAD

**Issue by xiao468657802** [run-nerver/imYun#1]
经过我一下午的试装，发现程序环境安装挺复杂的，而且独自占用3306的端口，个人绝的，这样的一个小程序，占用的资源太高了，相对的让人用QQ或微信发文档还是更便捷吧，（主要程序太复杂，占用资源多）

ql (1d3db81264036a82d929a3a0d4c146cf7710fed2de8f04f646d85a5a05095f48): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use

ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint mysql (1d3db81264036a82d929a3a0d4c146cf7710fed2de8f04f646d85a5a05095f48): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project.

3306,有一个mysql了

**Comment by run-nerver** [comment]
之所以做这个，是因为当地有打印店需求类似功能，当然目前只是雏形，谢谢建议。
下一步会继续优化
