### ISSUE TITLE
ERROR: Service 'web' failed to build 请求超时了

### ISSUE THREAD

**Issue by hubzy** [run-nerver/imYun#2]
您好；感谢你提供代码
我在运行 docker-compose up 之后报错了，请求超时了:(

Step 8/14 : FROM nginx:1.15.3-alpine as production-stage
ERROR: Service 'web' failed to build : Head https://registry-1.docker.io/v2/library/nginx/manifests/1.15.3-alpine: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by run-nerver** [comment]
看提示应该是网络问题，可能用的是默认的docker源，建议修改为国内docker源。

**Comment by hubzy** [comment]
> 看提示应该是网络问题，可能用的是替代的docker源，建议修改为国内docker源。
非常感谢，问题已解决。确实是源的问题
