### ISSUE TITLE
上传1002验证错误。

### ISSUE THREAD

**Issue by hubzy** [run-nerver/imYun#3]
您好麻烦你了，我上传文件后后台提示验证验证无效，小程序借口1002验证错误🙏

imYun_backend | 0
imYun_backend | HS256���token���������������err: token contains an invalid number of segments
imYun_backend | HS256���token���������������err: token contains an invalid number of segments

**Comment by run-nerver** [comment]
下载源码，修改imYun_backend/config.repo.yaml下的wechat的appid和secret为自己小程序的。
可以看下readme下面公网部署部分
